trigger:
 - main
pool:
  vmImage: 'ubuntu-latest'

variables:
  ImageName: 'wolfgangofner/microservicedemo:$(Build.BuildId)'

 steps:
 - task: Docker@2
   displayName: Build an image
   inputs:
     repository: $(imageName)
     command: build
     Dockerfile: app/Dockerfile